# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7616eb2872158ebab2076a9ce36ee6aa0f5c332c006d887cbeff44c3d8c8ed0ceb79125e547991c8db6d07e56686671578cf93d8366679384e937a22b159bf56

test:
  secret_key_base: c4428d1ca1414267c3300a42d91e36a2dc82fe04e1dde58fed9a92083980723eecb81d51531a83aa2cd8f8fbb4be21fe57dd07840487bb4b968687ec9c1772a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
